# Generated by Django 2.2.1 on 2019-06-09 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=22, verbose_name='姓名')),
                ('user_identifier', models.CharField(blank=True, default='null', max_length=22, unique=True)),
                ('user_review_count', models.IntegerField(default=0)),
                ('user_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_average_stars', models.FloatField(default=0)),
                ('user_fans', models.IntegerField(default=0)),
                ('user_useful_votes', models.IntegerField(default=0)),
                ('user_funny_votes', models.IntegerField(default=0)),
                ('user_cool_votes', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
