# Generated by Django 2.2.1 on 2019-06-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190609_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-user_date'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
