# Generated by Django 2.2.1 on 2019-06-09 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=22, unique=True)),
                ('business_name', models.CharField(max_length=100, verbose_name='企业名')),
                ('business_address', models.CharField(max_length=100, verbose_name='企业地址')),
                ('business_city', models.CharField(max_length=100, verbose_name='企业城市')),
                ('business_state', models.CharField(max_length=100, verbose_name='企业所在州')),
                ('business_postal_code', models.CharField(max_length=20, verbose_name='邮编')),
                ('business_lat', models.FloatField(verbose_name='纬度')),
                ('business_long', models.FloatField(verbose_name='经度')),
                ('business_stars', models.FloatField(default=0.0, verbose_name='得分')),
                ('business_review_count', models.IntegerField(default=0, verbose_name='评论计数')),
                ('business_mon', models.CharField(blank=True, max_length=20, verbose_name='周一')),
                ('business_tue', models.CharField(blank=True, max_length=20, verbose_name='周二')),
                ('business_wed', models.CharField(blank=True, max_length=20, verbose_name='周三')),
                ('business_thu', models.CharField(blank=True, max_length=20, verbose_name='周四')),
                ('business_fri', models.CharField(blank=True, max_length=20, verbose_name='周五')),
                ('business_sat', models.CharField(blank=True, max_length=20, verbose_name='周六')),
                ('business_sun', models.CharField(blank=True, max_length=20, verbose_name='周日')),
            ],
            options={
                'ordering': ['-business_stars', '-business_review_count'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_stars', models.FloatField(default=0, verbose_name='评分')),
                ('review_text', models.TextField(verbose_name='评论')),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('review_useful_vote', models.IntegerField(default=0)),
                ('review_funny_vote', models.IntegerField(default=0)),
                ('review_cool_vote', models.IntegerField(default=0)),
                ('review_business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoringsystem.Business')),
                ('review_user_id', models.ForeignKey(on_delete=models.SET('用户已注销'), to='login.UserProfile')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_option', models.IntegerField(choices=[(1, 'Useful'), (2, 'Funny'), (3, 'Cool')], default=0, verbose_name='投票选择')),
                ('vote_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoringsystem.Review')),
                ('vote_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_text', models.CharField(max_length=100, verbose_name='便签')),
                ('tip_date', models.DateField(verbose_name='日期')),
                ('tip_business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoringsystem.Business')),
                ('tip_user_id', models.ForeignKey(on_delete=models.SET('用户已注销'), to='login.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_caption', models.CharField(max_length=100, verbose_name='类别')),
                ('photo_label', models.CharField(max_length=100, verbose_name='标题')),
                ('photo_image', models.ImageField(max_length=250, upload_to='business_img', verbose_name='图片')),
                ('photo_business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoringsystem.Business')),
            ],
        ),
    ]
