# Generated by Django 2.2.1 on 2019-06-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_caption',
            field=models.CharField(max_length=200, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_label',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
