# Generated by Django 2.2.1 on 2019-06-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoringsystem', '0002_auto_20190610_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-business_review_count']},
        ),
    ]
