# Generated by Django 2.2.1 on 2019-06-11 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoringsystem', '0003_auto_20190611_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='tip_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
    ]
