# Generated by Django 2.2.1 on 2019-06-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringsystem', '0004_auto_20190611_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='tip_text',
            field=models.CharField(max_length=500, verbose_name='便签'),
        ),
    ]
