# Generated by Django 2.2.1 on 2019-06-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringsystem', '0005_auto_20190611_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['-tip_date']},
        ),
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='企业名'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_stars',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='得分'),
        ),
    ]
